nelmio_api_doc:
    documentation:
        servers:
            - url: https://127.0.0.1:8080
              description: Local server
        info:
            title: API de Gestion des Produits
            description: API permettant de gérer le catalogue de produits
            version: 1.0.0
        components:
            schemas:
                Product:
                    type: object
                    properties:
                        id:
                            type: integer
                            readOnly: true
                        code:
                            type: string
                            minLength: 3
                            maxLength: 255
                        name:
                            type: string
                            minLength: 3
                            maxLength: 255
                        category:
                            type: string
                            minLength: 2
                            maxLength: 100
                        price:
                            type: number
                            format: float
                            minimum: 0
                        quantity:
                            type: integer
                            minimum: 0
                        description:
                            type: string
                            maxLength: 5000
                            nullable: true
                        image:
                            type: string
                            maxLength: 2048
                            nullable: true
                        internalReference:
                            type: string
                            maxLength: 255
                            nullable: true
                        shellId:
                            type: integer
                            nullable: true
                        inventoryStatus:
                            type: string
                            enum: [INSTOCK, LOWSTOCK, OUTOFSTOCK]
                            readOnly: true
                        rating:
                            type: number
                            format: float
                            minimum: 0
                            maximum: 5
                        createdAt:
                            type: string
                            format: date-time
                            readOnly: true
                        updatedAt:
                            type: string
                            format: date-time
                            readOnly: true
                CreateProductDTO:
                    type: object
                    required:
                        - code
                        - name
                        - category
                        - price
                        - quantity
                    properties:
                        code:
                            type: string
                            minLength: 3
                            maxLength: 255
                            description: "Code unique du produit"
                        name:
                            type: string
                            minLength: 3
                            maxLength: 255
                        category:
                            type: string
                            minLength: 2
                            maxLength: 100
                        price:
                            type: number
                            format: float
                            minimum: 0
                        quantity:
                            type: integer
                            minimum: 0
                        description:
                            type: string
                            maxLength: 5000
                            nullable: true
                        image:
                            type: string
                            maxLength: 2048
                            nullable: true
                        internalReference:
                            type: string
                            maxLength: 255
                            nullable: true
                        shellId:
                            type: integer
                            nullable: true
                        rating:
                            type: number
                            format: float
                            minimum: 0
                            maximum: 5
                            default: 0
                UpdateProductDTO:
                    type: object
                    properties:
                        code:
                            type: string
                            minLength: 3
                            maxLength: 255
                            nullable: true
                        name:
                            type: string
                            minLength: 3
                            maxLength: 255
                            nullable: true
                        category:
                            type: string
                            minLength: 2
                            maxLength: 100
                            nullable: true
                        price:
                            type: number
                            format: float
                            minimum: 0
                            nullable: true
                        quantity:
                            type: integer
                            minimum: 0
                            nullable: true
                        description:
                            type: string
                            maxLength: 5000
                            nullable: true
                        image:
                            type: string
                            maxLength: 2048
                            nullable: true
                        internalReference:
                            type: string
                            maxLength: 255
                            nullable: true
                        shellId:
                            type: integer
                            nullable: true
                        rating:
                            type: number
                            format: float
                            minimum: 0
                            maximum: 5
                            nullable: true
        paths:
            /api/products:
                get:
                    tags: ['Products']
                    summary: 'Récupère la liste des produits'
                    operationId: 'getAllProducts'
                    parameters:
                        - name: page
                          in: query
                          description: 'Numéro de page'
                          schema:
                              type: integer
                              default: 1
                        - name: limit
                          in: query
                          description: "Nombre d'éléments par page"
                          schema:
                              type: integer
                              default: 10
                    responses:
                        '200':
                            description: 'Liste des produits récupérée avec succès'
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            items:
                                                type: array
                                                items:
                                                    $ref: '#/components/schemas/Product'
                                            total:
                                                type: integer
                                            page:
                                                type: integer
                                            limit:
                                                type: integer
                                            lastPage:
                                                type: integer
                post:
                    tags: ['Products']
                    summary: 'Crée un nouveau produit'
                    operationId: 'createProduct'
                    requestBody:
                        required: true
                        description: "Note : L'inventoryStatus est automatiquement défini en fonction de la quantité"
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/CreateProductDTO'
                    responses:
                        '201':
                            description: 'Produit créé avec succès'
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Product'
                        '400':
                            description: 'Données invalides'

            '/api/products/{id}':
                get:
                    tags: ['Products']
                    summary: "Récupère les détails d'un produit"
                    operationId: 'getProduct'
                    parameters:
                        - name: id
                          in: path
                          required: true
                          description: 'ID du produit'
                          schema:
                              type: integer
                    responses:
                        '200':
                            description: 'Produit trouvé'
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Product'
                        '404':
                            description: 'Produit non trouvé'
                patch:
                    tags: ['Products']
                    summary: 'Met à jour un produit'
                    operationId: 'updateProduct'
                    parameters:
                        - name: id
                          in: path
                          required: true
                          description: 'ID du produit'
                          schema:
                              type: integer
                    requestBody:
                        required: true
                        description: "Mise à jour partielle : envoyez uniquement les champs à modifier"
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/UpdateProductDTO'
                    responses:
                        '200':
                            description: 'Produit mis à jour avec succès'
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Product'
                        '404':
                            description: 'Produit non trouvé'
                        '400':
                            description: 'Données invalides'
                delete:
                    tags: ['Products']
                    summary: 'Supprime un produit'
                    operationId: 'deleteProduct'
                    parameters:
                        - name: id
                          in: path
                          required: true
                          description: 'ID du produit'
                          schema:
                              type: integer
                    responses:
                        '204':
                            description: 'Produit supprimé avec succès'
                        '404':
                            description: 'Produit non trouvé'

    areas:
        path_patterns:
            - ^/api(?!/doc$)